// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOOA1xfS4KF416f0Ry7tLd8I8WfjkPfYw',
    appId: '1:749818574509:web:26958b168bb92291cfb824',
    messagingSenderId: '749818574509',
    projectId: 'uby01042023',
    authDomain: 'uby01042023.firebaseapp.com',
    storageBucket: 'uby01042023.appspot.com',
    measurementId: 'G-FKSXSZV4SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA18Y7Nik2zKbF9GncOs7Fu6WVGP-i9H1g',
    appId: '1:749818574509:android:070b927f2987984ccfb824',
    messagingSenderId: '749818574509',
    projectId: 'uby01042023',
    storageBucket: 'uby01042023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiQWL8a_cBgC03EbetlwhqduHspNG3Cjg',
    appId: '1:749818574509:ios:6d9d29201cc49db0cfb824',
    messagingSenderId: '749818574509',
    projectId: 'uby01042023',
    storageBucket: 'uby01042023.appspot.com',
    iosBundleId: 'com.ucuncubinyil.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiQWL8a_cBgC03EbetlwhqduHspNG3Cjg',
    appId: '1:749818574509:ios:6a9c2264cde994efcfb824',
    messagingSenderId: '749818574509',
    projectId: 'uby01042023',
    storageBucket: 'uby01042023.appspot.com',
    iosBundleId: 'com.ucuncubinyil.myapp.RunnerTests',
  );
}
